#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* CDR API
* Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMFileSanitizationApi: NSObject <CMApi>

extern NSString* kCMFileSanitizationApiErrorDomain;
extern NSInteger kCMFileSanitizationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Complete Content Disarm and Reconstruction on an Input File, and output in same file format
/// Processes the input file via CDR to produce a secured output file.  Input content is parsed, disarmed, and then reconstructed into a new output file with the same file format as the input.
///
/// @param inputFile Input document, or photos of a document, to extract data from (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) fileWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSError* error)) handler;


/// Complete Content Disarm and Reconstruction on an Input File with PDF/A Output
/// Processes the input file via CDR to produce a secured PDF/A output file.  Input content is parsed, disarmed, and then reconstructed into a new PDF/A output file.
///
/// @param inputFile Input document, or photos of a document, to extract data from (optional)
/// 
///  code:200 message:"OK"
///
/// @return void
-(NSURLSessionTask*) fileToPdfWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSError* error)) handler;



@end
