#import <Foundation/Foundation.h>
#import <AFNetworking/AFURLRequestSerialization.h>

/**
* CDR API
* Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface CMJSONRequestSerializer : AFJSONRequestSerializer
@end
